### ISSUE TITLE
关于debug状态开发单一module的问题

### ISSUE THREAD

**Issue by dante502** [myjoybar/Android-Router#2]
博主我看了你的源码之后有个问题，如果在debug状态下调试开发单一module时，测试同module跳转应该怎么做呢？博主你的路由初始化是在app module下进行的，那module的开发过程中，由于debug下使用的是module自己的Application，那么路由将不会初始化，这样的话是否会造成单module开发的不便呢？

**Comment by myjoybar** [comment]
你好！
第一个问题：module之间通过router跳转，module内则通过正常的startActivity进行跳转
第二个问题：在debug模式下，单一的module使用的是自己的debugApplication，必须保证和releaseApplication中实现的方法一样，才能保证最后打包到app时，对Application的使用无缝切换

最后，业务功能相对独立才能作为一个module，开发者应该更多的关注本module内的工作，而非和其它module对接。

**Comment by dante502** [comment]
> 你好！
> 第一个问题：module之间通过router跳转，module内则通过正常的startActivity进行跳转
> 第二个问题：在debug模式下，单一的module使用的是自己的debugApplication，必须保证和releaseApplication中实现的方法一样，才能保证最后打包到app时，对Application的使用无缝切换
> 
> 最后，业务功能相对独立才能作为一个module，开发者应该更多的关注本module内的工作，而非和其它module对接。

谢谢博主，完美的解答了我的疑问。
